'use strict'

/*
    ES5 and ES5-safe config
*/
module.exports = {
    extends: ['eslint:recommended'],
    rules: {
        'array-bracket-spacing': 2,
        'arrow-parens': [2, 'always'],
        'arrow-spacing': 2,
        'block-spacing': 2,
        'brace-style': [
            2,
            '1tbs',
            {allowSingleLine: true},
        ],
        'comma-spacing': 2,
        'comma-style': 2,
        'computed-property-spacing': 2,
        'consistent-this': [2, 'self'],
        curly: 2,
        'default-case': 2,
        'dot-notation': 2,
        'eol-last': 2,
        eqeqeq: [2, 'smart'],
        indent: 2,
        'key-spacing': 2,
        'keyword-spacing': 2,
        'linebreak-style': 2,
        'max-len': [
            2,
            100,
            4,
            {
                ignoreUrls: true,
                ignorePattern: '^import',
            },
        ],
        'max-params': [2, 5],
        'no-alert': 2,
        'no-const-assign': 2,
        'no-continue': 2,
        'no-dupe-class-members': 2,
        'no-else-return': 2,
        'no-eq-null': 2,
        'no-floating-decimal': 2,
        'no-implicit-coercion': [2, {boolean: false}],
        'no-label-var': 2,
        'no-loop-func': 2,
        'no-lonely-if': 2,
        'no-magic-numbers': [
            2,
            {
                ignore: [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                ],
            },
        ],
        'no-mixed-requires': 2,
        'no-multiple-empty-lines': [
            2,
            {
                max: 2,
                maxEOF: 1,
            },
        ],
        'no-native-reassign': 2,
        'no-param-reassign': [2, {props: true}],
        'no-path-concat': 2,
        'no-restricted-globals': [2, 'Promise'],
        'no-return-assign': 2,
        'no-shadow': 2,
        'no-shadow-restricted-names': 2,
        'no-template-curly-in-string': 2,
        'no-trailing-spaces': 2,
        'no-undef': 2,
        'no-undefined': 2,
        'no-unexpected-multiline': 2,
        'no-unneeded-ternary': 2,
        'no-unused-vars': 2,
        'no-use-before-define': [2, 'nofunc'],
        'no-useless-concat': 2,
        'object-curly-spacing': 2,
        'object-shorthand': [2, 'always'],
        'prefer-template': 2,
        quotes: [
            2,
            'single',
            'avoid-escape',
        ],
        'quote-props': [2, 'as-needed'],
        semi: [2, 'never'],
        'semi-spacing': 2,
        'space-in-parens': 2,
        'space-infix-ops': [2, {int32Hint: false}],
        'space-unary-ops': 2,
        'spaced-comment': [2, 'always'],
        strict: [2, 'global'],
        'template-curly-spacing': [2, 'never'],
        'valid-jsdoc': [
            2,
            {
                prefer: {
                    return: 'returns',
                },
            },
        ],
        'wrap-iife': 2,
        yoda: [
            2,
            'never',
            {exceptRange: true},
        ],
    },
}
